openapi: 3.0.3
info:
  title: Attendace-system(線上出勤管理系統)
  description: |
    提供企業員工使用線上打卡或 QRcode 方式掃碼打卡。
    打卡系統採用定位方式限制，不得於公司 400 公尺外進行系統登入。
  contact:
    email: ritachien929@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

# Domain of server(array)
servers:
  - description: Development
    url: http://localhost:3000
# Categories of APIs(array)
tags:
  - name: Auth
    description: 身分驗證相關路由。

# API paths
paths:
  /users/login:
    post:
      tags: [Auth]
      summary: 員工登入
      description: 員工輸入帳號/密碼登入成功後，server 會回傳身分驗證 Token。
      operationId: userLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account:
                  type: string
                  example: "user1"
                password:
                  type: string
                  example: "12345678"
              required: [account, password]
      responses:
        "200":
          description: 成功登入
        "401":
          description: 帳號或密碼錯誤
        "500":
          description: server error
